services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: app-php-8.3.8-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:1.17.1
    container_name: app-nginx-1.17.1
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge